import { Music2, Drum, Piano, Mic, Gamepad2, Brain } from "lucide-react";
import { LucideIcon } from "lucide-react";

export type GameStatus = "available" | "coming-soon" | "locked";

export interface GameConfig {
  id: string;
  title: string;
  description: string;
  route: string;
  status: GameStatus;
  icon: LucideIcon;
  color: string; // Tailwind color class
  difficulty?: "easy" | "medium" | "hard";
  ageRange?: string;
  thumbnail?: string;
}

export const games: GameConfig[] = [
  {
    id: "pitch-match",
    title: "High or Low?",
    description: "Learn to identify higher and lower pitched sounds with friendly animal musicians!",
    route: "/games/pitch-match",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "rhythm-echo-challenge",
    title: "Rhythm Echo Challenge",
    description: "Animals play a short rhythm; tap to echo the pattern.",
    route: "/games/rhythm-echo-challenge",
    status: "available",
    icon: Drum,
    color: "bg-purple-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "melody-memory-match",
    title: "Melody Memory Match",
    description: "Flip cards to hear melodies and match identical pairs.",
    route: "/games/melody-memory-match",
    status: "available",
    icon: Piano,
    color: "bg-green-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "fast-or-slow-race",
    title: "Fast or Slow Race",
    description: "Hear two tempos of the same tune; pick who played faster.",
    route: "/games/fast-or-slow-race",
    status: "available",
    icon: Gamepad2,
    color: "bg-orange-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "loud-or-quiet-safari",
    title: "Loud or Quiet Safari",
    description: "Same note, different volumes; who played louder or softer?",
    route: "/games/loud-or-quiet-safari",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "how-many-notes",
    title: "How Many Notes?",
    description: "Count how many notes are in a short sequence.",
    route: "/games/how-many-notes",
    status: "available",
    icon: Brain,
    color: "bg-pink-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "musical-simon-says",
    title: "Musical Simon Says",
    description: "Repeat growing pitch + rhythm sequences.",
    route: "/games/musical-simon-says",
    status: "available",
    icon: Gamepad2,
    color: "bg-orange-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "instrument-detective",
    title: "Instrument Detective",
    description: "Hear a sound and pick its instrument family.",
    route: "/games/instrument-detective",
    status: "available",
    icon: Mic,
    color: "bg-red-500",
    difficulty: "easy",
    ageRange: "6-9 years",
  },
  {
    id: "finish-the-tune",
    title: "Finish the Tune",
    description: "Hear the start of a melody; choose the correct ending.",
    route: "/games/finish-the-tune",
    status: "available",
    icon: Piano,
    color: "bg-green-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "long-or-short-notes",
    title: "Long or Short Notes?",
    description: "Compare note durations; who held the note longer?",
    route: "/games/long-or-short-notes",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "beat-keeper-challenge",
    title: "Beat Keeper Challenge",
    description: "Tap along with a steady beat for timing accuracy.",
    route: "/games/beat-keeper-challenge",
    status: "available",
    icon: Drum,
    color: "bg-purple-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "happy-or-sad-melodies",
    title: "Happy or Sad Melodies?",
    description: "Hear a melody and choose if it sounds happy or sad.",
    route: "/games/happy-or-sad-melodies",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "scale-climber",
    title: "Scale Climber",
    description: "Animal climbs up or down as a scale plays; pick the direction.",
    route: "/games/scale-climber",
    status: "available",
    icon: Gamepad2,
    color: "bg-orange-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "musical-pattern-detective",
    title: "Musical Pattern Detective",
    description: "Identify repeating patterns like ABA vs ABC.",
    route: "/games/musical-pattern-detective",
    status: "available",
    icon: Brain,
    color: "bg-pink-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "name-that-animal-tune",
    title: "Name That Animal Tune",
    description: "Hear a signature theme and pick the matching animal.",
    route: "/games/name-that-animal-tune",
    status: "available",
    icon: Piano,
    color: "bg-green-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "steady-or-bouncy-beat",
    title: "Steady or Bouncy Beat?",
    description: "Identify meter feel: march (4/4) vs waltz (3/4) vs swing (6/8).",
    route: "/games/steady-or-bouncy-beat",
    status: "available",
    icon: Drum,
    color: "bg-purple-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "musical-opposites",
    title: "Musical Opposites",
    description: "Match high/low, loud/soft, fast/slow, long/short.",
    route: "/games/musical-opposites",
    status: "available",
    icon: Brain,
    color: "bg-pink-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "pitch-ladder-jump",
    title: "Pitch Ladder Jump",
    description: "Did the pitch go up, down, or stay the same?",
    route: "/games/pitch-ladder-jump",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "rhythm-puzzle-builder",
    title: "Rhythm Puzzle Builder",
    description: "Arrange rhythm blocks (notes + rests) to match what you hear.",
    route: "/games/rhythm-puzzle-builder",
    status: "available",
    icon: Drum,
    color: "bg-purple-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "harmony-helper",
    title: "Harmony Helper",
    description: "Two notes together—do they sound consonant or dissonant?",
    route: "/games/harmony-helper",
    status: "available",
    icon: Piano,
    color: "bg-green-500",
    difficulty: "easy",
    ageRange: "6-9 years",
  },
  {
    id: "musical-freeze-dance",
    title: "Musical Freeze Dance",
    description: "Move or tap while music plays—freeze when it stops!",
    route: "/games/musical-freeze-dance",
    status: "available",
    icon: Gamepad2,
    color: "bg-orange-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "compose-your-song",
    title: "Compose Your Song",
    description: "Arrange animal notes to create and play your own melody.",
    route: "/games/compose-your-song",
    status: "available",
    icon: Piano,
    color: "bg-green-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "echo-location-challenge",
    title: "Echo Location Challenge",
    description: "Hear a sound from left or right—pick the side.",
    route: "/games/echo-location-challenge",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "easy",
    ageRange: "4-7 years",
  },
  {
    id: "musical-story-time",
    title: "Musical Story Time",
    description: "Choose story paths that change the music.",
    route: "/games/musical-story-time",
    status: "available",
    icon: Gamepad2,
    color: "bg-orange-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "tone-color-match",
    title: "Tone Color Match",
    description: "Match the same melody played on different instruments.",
    route: "/games/tone-color-match",
    status: "available",
    icon: Brain,
    color: "bg-pink-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "musical-math",
    title: "Musical Math",
    description: "Add and subtract note durations like quarters and halves.",
    route: "/games/musical-math",
    status: "available",
    icon: Brain,
    color: "bg-pink-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "rest-finder",
    title: "Rest Finder",
    description: "Count the quiet moments (rests) in a musical phrase.",
    route: "/games/rest-finder",
    status: "available",
    icon: Drum,
    color: "bg-purple-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "animal-orchestra-conductor",
    title: "Animal Orchestra Conductor",
    description: "Start/stop parts to layer percussion, melody, and harmony.",
    route: "/games/animal-orchestra-conductor",
    status: "available",
    icon: Gamepad2,
    color: "bg-orange-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "pitch-perfect-path",
    title: "Pitch Perfect Path",
    description: "Do higher platforms match higher notes along the path?",
    route: "/games/pitch-perfect-path",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "easy",
    ageRange: "5-8 years",
  },
  {
    id: "same-or-different",
    title: "Same or Different?",
    description: "Hear two phrases—are they identical or different?",
    route: "/games/same-or-different",
    status: "available",
    icon: Brain,
    color: "bg-pink-500",
    difficulty: "medium",
    ageRange: "6-9 years",
  },
  {
    id: "world-music-explorer",
    title: "World Music Explorer",
    description: "Match music styles to regions around the world.",
    route: "/games/world-music-explorer",
    status: "available",
    icon: Mic,
    color: "bg-red-500",
    difficulty: "easy",
    ageRange: "6-9 years",
  },
  {
    id: "staff-wars",
    title: "Staff Wars",
    description: "Read notes on the staff and tap before they reach the clef!",
    route: "/games/staff-wars",
    status: "available",
    icon: Music2,
    color: "bg-indigo-500",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "beat-and-pulse-trainer",
    title: "Beat & Pulse Trainer",
    description: "Keep a steady beat, tap along, internalize pulse, and practice subdivisions.",
    route: "/games/beat-and-pulse-trainer",
    status: "available",
    icon: Drum,
    color: "bg-purple-500",
    difficulty: "medium",
    ageRange: "6-12 years",
  },

  {
    id: "tempo-conducting-studio",
    title: "Tempo Conducting Studio",
    description: "Conduct tempo, set BPM by baton, make smooth transitions, and coordinate parts.",
    route: "/games/tempo-conducting-studio",
    status: "available",
    icon: Drum,
    color: "bg-purple-600",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "tempo-and-pulse-master",
    title: "Tempo & Pulse Master",
    description: "Master tempo recognition, tempo changes, pulse subdivisions, and tempo analysis.",
    route: "/games/tempo-and-pulse-master",
    status: "available",
    icon: Drum,
    color: "bg-indigo-500",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "rhythm-master",
    title: "Rhythm Master",
    description: "Master rhythmic patterns, transformations, and analysis.",
    route: "/games/rhythm-master",
    status: "available",
    icon: Drum,
    color: "bg-purple-500",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "pitch-001",
    title: "Pitch Explorer",
    description: "Master the characteristics and qualities of musical pitch through exploration of octaves, pitch modifications, and timbral elements.",
    route: "/games/pitch-001",
    status: "available",
    icon: Music2,
    color: "bg-blue-500",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "pitch-002",
    title: "Interval Trainer",
    description: "Develop ear training skills through interval recognition, relative pitch, and absolute pitch.",
    route: "/games/pitch-002",
    status: "available",
    icon: Music2,
    color: "bg-blue-600",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "pitch-003",
    title: "Melody Master",
    description: "Understand how melodies transform and evolve through transposition, inversion, retrograde, and patterns.",
    route: "/games/pitch-003",
    status: "available",
    icon: Music2,
    color: "bg-blue-700",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "pitch-004",
    title: "Phrase Analyzer",
    description: "Learn how music creates sentences and paragraphs through phrase structure, boundaries, and relationships.",
    route: "/games/pitch-004",
    status: "available",
    icon: Music2,
    color: "bg-cyan-500",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "pitch-005",
    title: "Scale & Mode Master",
    description: "Explore the tonal frameworks that organize music through major/minor scales, church modes, and special scales.",
    route: "/games/pitch-005",
    status: "available",
    icon: Music2,
    color: "bg-cyan-600",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "pitch-006",
    title: "Contour Master",
    description: "Master melodic shape and direction through contour transformations and analysis.",
    route: "/games/pitch-006",
    status: "available",
    icon: Music2,
    color: "bg-cyan-700",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "rhythm-003",
    title: "Meter Master",
    description: "Master time signatures and metric organization through common meters, compound meters, and mixed meters.",
    route: "/games/rhythm-003",
    status: "available",
    icon: Drum,
    color: "bg-purple-600",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "rhythm-004",
    title: "Rhythm Notation Master",
    description: "Develop fluency in reading and writing rhythm through note/rest values, beaming, and notation.",
    route: "/games/rhythm-004",
    status: "available",
    icon: Drum,
    color: "bg-purple-700",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "rhythm-005",
    title: "Polyrhythm Master",
    description: "Master multiple simultaneous rhythms through identification and performance.",
    route: "/games/rhythm-005",
    status: "available",
    icon: Drum,
    color: "bg-purple-800",
    difficulty: "hard",
    ageRange: "8-12 years",
  },
  {
    id: "harmony-001",
    title: "Interval Master",
    description: "Master the building blocks of harmony through all intervals.",
    route: "/games/harmony-001",
    status: "available",
    icon: Music2,
    color: "bg-green-500",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "harmony-002",
    title: "Chord Master",
    description: "Master vertical harmony structures through triads, seventh chords, and extended chords.",
    route: "/games/harmony-002",
    status: "available",
    icon: Music2,
    color: "bg-green-600",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "harmony-003",
    title: "Harmonic Progression Master",
    description: "Master chord sequences and harmonic movement through common progressions.",
    route: "/games/harmony-003",
    status: "available",
    icon: Music2,
    color: "bg-green-700",
    difficulty: "medium",
    ageRange: "8-12 years",
  },
  {
    id: "harmony-004",
    title: "Consonance & Dissonance Master",
    description: "Master tension and release through consonance, dissonance, and resolution.",
    route: "/games/harmony-004",
    status: "available",
    icon: Music2,
    color: "bg-green-800",
    difficulty: "medium",
    ageRange: "8-12 years",
  },
  {
    id: "timbre-001",
    title: "Instrument Master",
    description: "Master instrument recognition, families, and characteristics.",
    route: "/games/timbre-001",
    status: "available",
    icon: Music2,
    color: "bg-orange-500",
    difficulty: "easy",
    ageRange: "6-12 years",
  },
  {
    id: "timbre-002",
    title: "Timbre Analyzer",
    description: "Master timbre recognition, comparison, and analysis.",
    route: "/games/timbre-002",
    status: "available",
    icon: Music2,
    color: "bg-orange-600",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "timbre-003",
    title: "Performance Technique Explorer",
    description: "Master performance techniques, articulations, and effects.",
    route: "/games/timbre-003",
    status: "available",
    icon: Music2,
    color: "bg-orange-700",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "dynamics-001",
    title: "Dynamics Master",
    description: "Master volume levels, crescendo/diminuendo, and dynamic markings.",
    route: "/games/dynamics-001",
    status: "available",
    icon: Music2,
    color: "bg-red-500",
    difficulty: "easy",
    ageRange: "6-12 years",
  },
  {
    id: "dynamics-002",
    title: "Expression Master",
    description: "Master expression markings, phrasing, and articulation.",
    route: "/games/dynamics-002",
    status: "available",
    icon: Music2,
    color: "bg-red-600",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "dynamics-003",
    title: "Emotion Master",
    description: "Master emotional recognition, expression, and mood analysis.",
    route: "/games/dynamics-003",
    status: "available",
    icon: Music2,
    color: "bg-red-700",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "theory-001",
    title: "Note Reading Master",
    description: "Master note reading in treble clef, bass clef, alto clef, and ledger lines.",
    route: "/games/theory-001",
    status: "available",
    icon: Music2,
    color: "bg-yellow-500",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "theory-002",
    title: "Scale Builder",
    description: "Master scale construction, identification, and analysis.",
    route: "/games/theory-002",
    status: "available",
    icon: Music2,
    color: "bg-yellow-600",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "theory-003",
    title: "Chord Builder",
    description: "Master chord construction, identification, and analysis.",
    route: "/games/theory-003",
    status: "available",
    icon: Music2,
    color: "bg-yellow-700",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "theory-004",
    title: "Key Signature Master",
    description: "Master major keys, minor keys, and key identification.",
    route: "/games/theory-004",
    status: "available",
    icon: Music2,
    color: "bg-yellow-800",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "compose-001",
    title: "Composition Studio",
    description: "Master melody composition, harmony composition, and arrangement.",
    route: "/games/compose-001",
    status: "available",
    icon: Music2,
    color: "bg-pink-500",
    difficulty: "hard",
    ageRange: "8-12 years",
  },
  {
    id: "compose-002",
    title: "Orchestration & Style Studio",
    description: "Master orchestration, style analysis, and arrangement techniques.",
    route: "/games/compose-002",
    status: "available",
    icon: Music2,
    color: "bg-pink-600",
    difficulty: "hard",
    ageRange: "9-12 years",
  },
  {
    id: "listen-001",
    title: "Musical Form Explorer",
    description: "Master form recognition, analysis, and composition.",
    route: "/games/listen-001",
    status: "available",
    icon: Music2,
    color: "bg-teal-500",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "listen-002",
    title: "Musical Style Detective",
    description: "Master style recognition, period identification, and composer analysis.",
    route: "/games/listen-002",
    status: "available",
    icon: Music2,
    color: "bg-teal-600",
    difficulty: "medium",
    ageRange: "8-12 years",
  },
  {
    id: "listen-003",
    title: "Composer Detective",
    description: "Master composer recognition, work identification, and style analysis.",
    route: "/games/listen-003",
    status: "available",
    icon: Music2,
    color: "bg-teal-700",
    difficulty: "medium",
    ageRange: "8-12 years",
  },
  {
    id: "listen-004",
    title: "Musical Elements Analyzer",
    description: "Master element recognition, analysis, and composition.",
    route: "/games/listen-004",
    status: "available",
    icon: Music2,
    color: "bg-teal-800",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "cross-001",
    title: "Music & Math Explorer",
    description: "Master ratios, patterns, and sequences in music.",
    route: "/games/cross-001",
    status: "available",
    icon: Music2,
    color: "bg-indigo-600",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "cross-002",
    title: "Music & Language Lab",
    description: "Master lyrics, poetry, and storytelling in music.",
    route: "/games/cross-002",
    status: "available",
    icon: Music2,
    color: "bg-indigo-700",
    difficulty: "medium",
    ageRange: "7-12 years",
  },
  {
    id: "cross-003",
    title: "Music & Movement Studio",
    description: "Master movement, choreography, and gesture in music.",
    route: "/games/cross-003",
    status: "available",
    icon: Music2,
    color: "bg-indigo-800",
    difficulty: "medium",
    ageRange: "6-12 years",
  },
  {
    id: "advanced-001",
    title: "Advanced Music Analyzer",
    description: "Master advanced analysis, composition, and performance.",
    route: "/games/advanced-001",
    status: "available",
    icon: Music2,
    color: "bg-gray-700",
    difficulty: "hard",
    ageRange: "10-12 years",
  },
  {
    id: "challenge-001",
    title: "Musical Skills Arena",
    description: "Master challenges, competitions, and mastery across all skills.",
    route: "/games/challenge-001",
    status: "available",
    icon: Music2,
    color: "bg-gray-800",
    difficulty: "hard",
    ageRange: "8-12 years",
  },


];

export const getGameById = (id: string): GameConfig | undefined => {
  return games.find((game) => game.id === id);
};

export const getAvailableGames = (): GameConfig[] => {
  return games.filter((game) => game.status === "available");
};

export const getComingSoonGames = (): GameConfig[] => {
  return games.filter((game) => game.status === "coming-soon");
};

