import type { BossEncounter } from '@shared/types/cadence-quest';

export const BOSSES: BossEncounter[] = [
  {
    id: 'metronome-mage',
    name: 'Chronos',
    title: 'The Metronome Mage',
    regionId: 'rhythm-realm',
    description: 'Master of tempo and timing',
    spritePath: '/images/cadence-quest/bosses/metronome-mage.svg',
    emoji: '⏱️',
    maxHp: 150,
    level: 5,
    stages: [
      {
        order: 1,
        discipline: 'rhythm',
        difficulty: 'medium',
        correctAnswerDamage: 25,
        wrongAnswerDamage: 15,
        timeLimit: 20,
      },
      {
        order: 2,
        discipline: 'rhythm',
        difficulty: 'medium',
        correctAnswerDamage: 30,
        wrongAnswerDamage: 20,
        abilityTrigger: 'tempo-shift',
      },
      {
        order: 3,
        discipline: 'rhythm',
        difficulty: 'hard',
        correctAnswerDamage: 35,
        wrongAnswerDamage: 25,
        comboRequired: 2,
      },
    ],
    abilities: [
      {
        id: 'tempo-shift',
        name: 'Tempo Shift',
        description: 'Increases challenge speed by 20%',
        trigger: 'on_stage_start',
        triggerValue: 2,
        effect: {
          type: 'environment_change',
          duration: 1,
          value: 1.2,
        },
        soundEffect: 'tempo-shift.wav',
      },
      {
        id: 'rhythm-mirror',
        name: 'Rhythm Mirror',
        description: 'Reflects 50% of damage back to player',
        trigger: 'on_hp_threshold',
        triggerValue: 50,
        effect: {
          type: 'buff_self',
          duration: 2,
          value: 0.5,
        },
      },
    ],
    guaranteedDrops: [],
    possibleDrops: [],
    xpReward: 500,
    goldReward: 300,
    flavorText: 'Time flows differently in the Rhythm Realm...',
    defeatQuote: 'Your timing... is impeccable...',
  },
  {
    id: 'siren-sovereign',
    name: 'Aria',
    title: 'The Siren Sovereign',
    regionId: 'melody-mountains',
    description: 'Her voice can shatter mountains',
    spritePath: '/images/cadence-quest/bosses/siren.svg',
    emoji: '👸',
    maxHp: 180,
    level: 10,
    stages: [
      {
        order: 1,
        discipline: 'pitch',
        difficulty: 'medium',
        correctAnswerDamage: 30,
        wrongAnswerDamage: 18,
      },
      {
        order: 2,
        discipline: 'pitch',
        difficulty: 'hard',
        correctAnswerDamage: 35,
        wrongAnswerDamage: 22,
        abilityTrigger: 'siren-song',
      },
      {
        order: 3,
        discipline: 'pitch',
        difficulty: 'hard',
        correctAnswerDamage: 40,
        wrongAnswerDamage: 28,
        comboRequired: 3,
      },
    ],
    abilities: [
      {
        id: 'siren-song',
        name: 'Siren Song',
        description: 'Confuses the player, swapping answer options',
        trigger: 'on_stage_start',
        triggerValue: 2,
        effect: {
          type: 'debuff_player',
          duration: 1,
          value: 1,
        },
      },
      {
        id: 'perfect-pitch-aura',
        name: 'Perfect Pitch Aura',
        description: 'Heals 10% HP on correct answer',
        trigger: 'on_correct',
        effect: {
          type: 'heal',
          value: 0.1,
        },
      },
    ],
    guaranteedDrops: [],
    possibleDrops: [],
    xpReward: 800,
    goldReward: 450,
    flavorText: 'Only those with perfect pitch may pass...',
    defeatQuote: 'Your melody... surpasses even mine...',
  },
  {
    id: 'chord-kraken',
    name: 'Harmonia',
    title: 'The Chord Kraken',
    regionId: 'harmony-harbor',
    description: 'Guardian of harmonic secrets',
    spritePath: '/images/cadence-quest/bosses/kraken.svg',
    emoji: '🦑',
    maxHp: 220,
    level: 15,
    stages: [
      {
        order: 1,
        discipline: 'harmony',
        difficulty: 'medium',
        correctAnswerDamage: 35,
        wrongAnswerDamage: 20,
      },
      {
        order: 2,
        discipline: 'harmony',
        difficulty: 'hard',
        correctAnswerDamage: 40,
        wrongAnswerDamage: 25,
        abilityTrigger: 'dissonance-wave',
      },
      {
        order: 3,
        discipline: 'harmony',
        difficulty: 'hard',
        correctAnswerDamage: 45,
        wrongAnswerDamage: 30,
        comboRequired: 3,
      },
    ],
    abilities: [
      {
        id: 'dissonance-wave',
        name: 'Dissonance Wave',
        description: 'Reduces player accuracy by 15%',
        trigger: 'on_stage_start',
        triggerValue: 2,
        effect: {
          type: 'debuff_player',
          duration: 2,
          value: 0.15,
        },
      },
      {
        id: 'harmonic-shield',
        name: 'Harmonic Shield',
        description: 'Absorbs next 30 damage',
        trigger: 'on_hp_threshold',
        triggerValue: 40,
        effect: {
          type: 'buff_self',
          value: 30,
        },
      },
    ],
    guaranteedDrops: [],
    possibleDrops: [],
    xpReward: 1200,
    goldReward: 600,
    flavorText: 'The depths hold many harmonic mysteries...',
    defeatQuote: 'Your resonance... rings true...',
  },
  {
    id: 'fortress-phoenix',
    name: 'Crescendo',
    title: 'The Fortress Phoenix',
    regionId: 'dynamics-desert',
    description: 'Born from the loudest crescendo',
    spritePath: '/images/cadence-quest/bosses/phoenix.svg',
    emoji: '🔥',
    maxHp: 260,
    level: 20,
    stages: [
      {
        order: 1,
        discipline: 'dynamics',
        difficulty: 'medium',
        correctAnswerDamage: 40,
        wrongAnswerDamage: 25,
      },
      {
        order: 2,
        discipline: 'dynamics',
        difficulty: 'hard',
        correctAnswerDamage: 45,
        wrongAnswerDamage: 30,
        abilityTrigger: 'fortissimo-burst',
      },
      {
        order: 3,
        discipline: 'dynamics',
        difficulty: 'hard',
        correctAnswerDamage: 50,
        wrongAnswerDamage: 35,
        comboRequired: 3,
      },
    ],
    abilities: [
      {
        id: 'fortissimo-burst',
        name: 'Fortissimo Burst',
        description: 'Deals 40 damage to player',
        trigger: 'on_stage_start',
        triggerValue: 2,
        effect: {
          type: 'environment_change',
          value: 40,
        },
      },
      {
        id: 'phoenix-rebirth',
        name: 'Phoenix Rebirth',
        description: 'Heals 20% HP when below 30%',
        trigger: 'on_hp_threshold',
        triggerValue: 30,
        effect: {
          type: 'heal',
          value: 0.2,
        },
      },
    ],
    guaranteedDrops: [],
    possibleDrops: [],
    xpReward: 1500,
    goldReward: 750,
    flavorText: 'From piano to fortissimo, I have risen...',
    defeatQuote: 'Even in silence... my legacy endures...',
  },
  {
    id: 'grand-maestro',
    name: 'Maestro Fortissimo',
    title: 'The Grand Maestro',
    regionId: 'theory-tower',
    description: 'The ultimate musical challenge',
    spritePath: '/images/cadence-quest/bosses/maestro.svg',
    emoji: '🎼',
    maxHp: 350,
    level: 25,
    stages: [
      {
        order: 1,
        discipline: 'theory',
        difficulty: 'hard',
        correctAnswerDamage: 50,
        wrongAnswerDamage: 30,
      },
      {
        order: 2,
        discipline: 'theory',
        difficulty: 'hard',
        correctAnswerDamage: 55,
        wrongAnswerDamage: 35,
        abilityTrigger: 'counterpoint-storm',
      },
      {
        order: 3,
        discipline: 'theory',
        difficulty: 'hard',
        correctAnswerDamage: 60,
        wrongAnswerDamage: 40,
        comboRequired: 4,
      },
      {
        order: 4,
        discipline: 'theory',
        difficulty: 'hard',
        correctAnswerDamage: 70,
        wrongAnswerDamage: 50,
        timeLimit: 15,
        abilityTrigger: 'final-crescendo',
      },
    ],
    abilities: [
      {
        id: 'counterpoint-storm',
        name: 'Counterpoint Storm',
        description: 'Mixes all challenge types randomly',
        trigger: 'on_stage_start',
        triggerValue: 2,
        effect: {
          type: 'environment_change',
          duration: 2,
          value: 1,
        },
      },
      {
        id: 'theory-mastery',
        name: 'Theory Mastery',
        description: 'All damage reduced by 30%',
        trigger: 'on_hp_threshold',
        triggerValue: 50,
        effect: {
          type: 'buff_self',
          duration: 99,
          value: 0.3,
        },
      },
      {
        id: 'final-crescendo',
        name: 'Final Crescendo',
        description: 'Doubles damage for both players',
        trigger: 'on_stage_start',
        triggerValue: 4,
        effect: {
          type: 'environment_change',
          duration: 1,
          value: 2.0,
        },
      },
    ],
    guaranteedDrops: [],
    possibleDrops: [],
    xpReward: 2500,
    goldReward: 1200,
    flavorText: 'You have climbed far, but theory is infinite...',
    defeatQuote: 'At last... a true master of music...',
  },
];

export function getBossByRegion(regionId: string): BossEncounter | undefined {
  return BOSSES.find(boss => boss.regionId === regionId);
}

export function getBossById(bossId: string): BossEncounter | undefined {
  return BOSSES.find(boss => boss.id === bossId);
}